const SHOW_ALERT = 'SHOW_ALERT';
const HIDE_ALERT = 'HIDE_ALERT';
const SHOW_LOADER = 'SHOW_LOADER';
const ADD_ITEM = 'ADD_ITEM';
const FETCH_ITEMS = 'FETCH_ITEMS';
const REMOVE_ITEMS = 'REMOVE_ITEMS';

export {
    SHOW_ALERT,
    HIDE_ALERT,
    SHOW_LOADER,
    ADD_ITEM,
    FETCH_ITEMS,
    REMOVE_ITEMS
};